openapi: "3.0.0"
info:
  title: Task Management System
  description: Manage your task easily
  version: 1.1.0
  contact:
    email: khanalgaurab98@gmail.com

servers:
  - url: "{protocol}://{url}/api/{version}"
    description: for local host 
    variables:
      version:
        enum:
          - v1
        default: v1
      url:
        enum:
          - localhost:4000
          - taskmanagementbackend-production-7cd5.up.railway.app
        default: taskmanagementbackend-production-7cd5.up.railway.app
      protocol:
        enum:
          - http
          - https
        default: https


paths:
  /test:
    get:
      tags:
        - Home
      summary: returns Hello World
      responses:
        200:
          description: All good success
          content:
            application/json:
              schema:
                type: string
                example: "mystring"
        400:
          description: Bad request
        500:
          description: internal server error
  
  /add:
    post:
      tags:
        - Task Management CRUD
      summary: Create a new task
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                title:
                  type: string
                status:
                  type: string
                  enum:
                    - unstarted
                    - pending
                    - completed
              required:
                - title
                - status
      responses:
        200:
          description: Task added successfully
  
  /allTask:
    get:
      tags:
        - Task Management CRUD
      summary: Get all tasks
      responses:
        200:
          description: List of tasks

  /singleTask/{id}:
    get:
      tags:
        - Task Management CRUD
      summary: Get task by ID
      parameters:
        - name: id
          in: path
          type: string
          required: true
          description: Task ID
      responses:
        200:
          description: Task details

  /category/{status}:
    get:
      tags:
        - Task Management CRUD
      summary: Get tasks by status
      parameters:
        - name: status
          in: path
          schema:
            type: string
            required: true
            description: Task status
            enum:
              - unstarted
              - pending
              - completed
            default: unstarted
      responses:
        200:
          description: List of tasks by status
  
  /updateTask/{id}:
     put:
      tags:
        - Task Management CRUD
      summary: Update task by ID
      parameters:
        - name: id
          in: path
          required: true
          description: Task ID
          schema:
            type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                title:
                  type: string
                status:
                  type: string
                  enum:
                    - unstarted
                    - pending
                    - completed
              required:
                - title
                - status
      responses:
        200:
          description: Task Updated successfully
  

  /deleteTask/{id}:
    delete:
      tags:
        - Task Management CRUD
      summary: Delete task by ID
      parameters:
        - name: id
          in: path
          type: string
          required: true
          description: Task ID
      responses:
        200:
          description: Task deleted successfully
